spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8083
name: johnny5v
age: 33
content: "Jeg heter ${name} -dev env"


